Dx improvements
cheqd/wallet pull request #67
Opened 2022-09-23 09:57 UTC by jay-dee7

2022-09-23 10:01 UTC, jay-dee7 commented
build fails right now because of some issue with `vite+rematch`. working on a fix right now

2022-09-23 14:10 UTC, jay-dee7 commented
Build still fails, even though it actually succeeded but there's still a dependency issue with `vite build` about `Buffer` but that's the only thing left right now.
This one could be the answer to it but it looks too basic https://stackoverflow.com/questions/70714690/buffer-is-not-defined-in-react-vite

2022-09-23 14:31 UTC, jay-dee7 commented
The components library work: [our fork of frontend-elements](https://github.com/cheqd/frontend-elements/tree/convert-to-lib)

2022-10-03 09:01 UTC, jay-dee7 commented
There's one more UI bug that needs fixing. This happens for notifications in dark mode
![SCR-20220930-tg9](https://user-images.githubusercontent.com/10788442/193539446-ec1ad52b-166a-49dc-a04b-ab5cecf4291c.png)

2022-10-03 12:45 UTC, jay-dee7 commented
> There's one more UI bug that needs fixing. This happens for notifications in dark mode ![SCR-20220930-tg9](https://user-images.githubusercontent.com/10788442/193539446-ec1ad52b-166a-49dc-a04b-ab5cecf4291c.png)

This one is fixed

2022-10-14 20:08 UTC, ankurdotb requested changes

2022-10-14 20:08 UTC, ankurdotb commented on src/constant/index.ts
> +export const IS_TESTNET = import.meta.env.VITE_RPC_ENDPOINT.includes('network');
Review this file in general. Looks like there's a lot of unused or incorrect URLs/variables? Are they needed/can be removed, or replaced with something more sensible?

I've also been thinking that maybe we should sync from upstream Lum frontend-elements repo as well as wallets, so maybe it's better to keep this separate and deal with it in that PR?

2022-10-14 20:08 UTC, ankurdotb commented on package.json
> +        "@ledgerhq/hw-transport-webusb": "^6.27.4",
Do we currently support ledger devices? Consider ditching if it doesn't work, otherwise fine.

2022-10-14 20:08 UTC, ankurdotb commented on package.json
> +        "@lum-network/sdk-javascript": "^0.7.6",
We do have a fork of [sdk-javascript](https://github.com/cheqd/sdk-javascript). Aren't we supposed to be using this fork, rather than upstream? I don't have an opinion either way, but I think there was a reason we created the fork in the first place (was it because we had some fixes there?)

2022-10-14 20:08 UTC, ankurdotb commented on src/redux/models/wallet.ts
> +								}
Incorrect, so I've updated to the correct values but in general might need a closer sweep

2022-10-14 20:08 UTC, ankurdotb commented on src/screens/Staking/components/Lists/styles/Lists.scss
> +@import '../../../../../styles//main';
Is the `//` correct?

2022-10-17 12:17 UTC, jay-dee7 commented on package.json
> +        "@lum-network/sdk-javascript": "^0.7.6",
@ankurdotb we actually don't rely on lum-sdk much. Our goal is to phase it out. So far, what I can see is that the entire registry uses cosmjs and we mostly use util functions from the lum-sdk. Slowly, we've remove it so I guess it's okay for it to be here like this

2022-10-17 12:19 UTC, jay-dee7 commented on package.json
> +        "@ledgerhq/hw-transport-webusb": "^6.27.4",
We actually do. I never got to test them but I believe they should work just fine?

2022-10-17 13:06 UTC, jay-dee7 commented on src/constant/index.ts
> +export const IS_TESTNET = import.meta.env.VITE_RPC_ENDPOINT.includes('network');
@ankurdotb I've removed whatever I could without much effort. I can track rest with the upstream changes in a different task/PR?

2022-10-18 12:11 UTC, ankurdotb approved these changes

2022-10-18 12:14 UTC, merged