Sign txn with mnemonic
cheqd/wallet pull request #8
Opened 2022-05-04 06:10 UTC by jay-dee7

2022-05-11 09:01 UTC, Eengineer1 requested changes
- Typo fixed
- Messages tab is removed
- Transaction signing works
- Denomination fixed

Yet to be fixed
- Correct showing of vested vs vesting breakdown.


Great work so far!

2022-05-11 09:01 UTC, Eengineer1 commented on src/network/cheqd.ts
> +			{ amount: [{ denom: NanoCheqDenom, amount: '12000' }], gas: '1' },
@jay-dee7 Shouldn't gas be 0 here?

2022-05-11 09:01 UTC, Eengineer1 commented on src/network/cheqd.ts
> +			// @ts-ignore
Why to ignore type checking?

2022-05-11 09:01 UTC, Eengineer1 commented on src/redux/models/identity.ts
> -import { Credential, IdentityWallet, RootModel } from '../../models';
@jay-dee7 Why to remove basic identity helpers? Is importing replaced at another point?

2022-05-11 09:07 UTC, jay-dee7 commented on src/redux/models/identity.ts
> -import { Credential, IdentityWallet, RootModel } from '../../models';
these imports are unused so I removed them

2022-05-11 09:08 UTC, jay-dee7 commented on src/network/cheqd.ts
> +			{ amount: [{ denom: NanoCheqDenom, amount: '12000' }], gas: '1' },
yeah actually it can be zero, will update that asap

2022-05-12 06:28 UTC, jay-dee7 commented on src/network/cheqd.ts
> +			{ amount: [{ denom: NanoCheqDenom, amount: '12000' }], gas: '1' },
I see, we don't need this method at all so i'm removing it now

2022-05-12 06:28 UTC, jay-dee7 commented on src/network/cheqd.ts
> +			// @ts-ignore
that was just wrong I guess. Removing the comment now

2022-05-12 21:41 UTC, merged